# for each folder in anda/
# generate a new workflow for each folder in anda/
name: Build all packages
on:
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
      options: --cap-add=SYS_ADMIN --privileged -v /dev:/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: deps
        run: dnf install -y git moby-engine

      - name: Cache buildroot
        id: br-cache
        uses: actions/cache@v3
        with:
          path: /var/cache
          key: ${{ runner.os }}-br-all
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build with Andaman
        run: |
          mkdir -p /etc/mock/templates
          ln -svfr ./aoyama.tpl /etc/mock/templates/aoyama.tpl
          anda build --all --package rpm -c $PWD/${{ matrix.arch }}.cfg

      - name: Generating artifact name
        id: art
        run: |
          echo "name=all-packages" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.art.outputs.name }}
          path: anda-build/rpm/rpms/*